### ISSUE TITLE
Present meaningful info when opening description files

### ISSUE THREAD

**Issue by bonsak** [nr-plugins/resedit#15]
As ResEdit can't edit description files the plugin should present the user with a plain text warning when opening such files instead of todays message: "There was an error loading the file:  Line: 1 Symbol: CONTAINER"

**Comment by NiklasRosenstein** [comment]
I'd keep it as it is. ResEdit is a tool for developers, and the developer would know something about the tool and environment they're using. From the technical standpoint, the error message makes perfect sense.

**Comment by bonsak** [comment]
Ok :)
