### ISSUE TITLE
Add Close or Cancel button in Make Distribution dialog

### ISSUE THREAD

**Issue by bonsak** [nr-plugins/resedit#17]
The Make Distribution dialog does not have a Close or Cancel button.
![make-dist-dialog](https://cloud.githubusercontent.com/assets/1322824/11014596/e0fe801e-853d-11e5-8306-970242fdd58c.jpg)

**Comment by NiklasRosenstein** [comment]
Aye, modal dialogs on Mac have no buttons in the window titlebar.

**Comment by NiklasRosenstein** [comment]
I don't think there is supposed to be a "Close" or "Cancel" button. The "Ok" button does nothing but closing the dialog.

**Comment by NiklasRosenstein** [comment]
I've never used this dialog though, I don't even understand what it's used for.

**Comment by bonsak** [comment]
Me neither :) just seemed weird with no cancel button. No biggie.
