### ISSUE TITLE
Point Help menu item to the UI section in the C++ API

### ISSUE THREAD

**Issue by bonsak** [nr-plugins/resedit#18]
Help menu item doesn't do any thing. Consider pointing this to the UI section in the C++ API: https://developers.maxon.net/docs/Cinema4DCPPSDK/html/page_user_interface.html

**Comment by NiklasRosenstein** [comment]
It is supposed to open the documentation files in the plugin folder, but they are not in the repository nor in the official [download](https://developers.maxon.net/?page_id=1118) from the PluginCafe. Pointing it to the UI section in the C++ API is a good idea.
