### ISSUE TITLE
Remove width restriction on Browser- and Properties dialogs

### ISSUE THREAD

**Issue by bonsak** [nr-plugins/resedit#3]
Both these dialogs have minimum width constraints. When they are docked into layouts they lock up some of adjustability of the layout.

**Comment by NiklasRosenstein** [comment]
@bonsak  That would require to wrap both dialogs in a scroll group. Personally, I don't really like scrolling the full dialog, especially not horizontally. How do you dock them in your layout? (screenshot) Just to get a glimpse.

**Comment by bonsak** [comment]
@NiklasRosenstein 
![minumum-width](https://cloud.githubusercontent.com/assets/1322824/10975515/a4466b02-83e7-11e5-9fa5-03802c3be47e.jpg)
Just opened ResEdit in ResEdit :) And checked out IDC_PROPERTIES_DIALOG.res There seems to be absolute width values on some of the elements. Thats whats constraining the width.
https://github.com/bonsak/resedit/commit/f6f1127a0f9cd268e3cf97973ffbea69d60747f4

**Comment by bonsak** [comment]
Not really that good with dialogs so i'm not sure how to make those values percentages instead.

**Comment by NiklasRosenstein** [comment]
@bonsak  It looks like the text at the bottom of the "Browser" windows is restricting the window size. String fields in Cinema always consume the space they need to display the text.

**Comment by bonsak** [comment]
Agree. I managed to change width restriction in the Browser dialog by changing: 
ALIGN_TOP; SCALE_H; SIZE 0, 50;  // To 50 instead of 100
Line 37 in IDC_CMP_RES_ST_TABLE.res

**Comment by NiklasRosenstein** [comment]
@bonsak  I've overcome this by removing the two text fields. I've also put the "Browse" button into the menu line and the currently displayed folder into the title bar. I'd like to show the absolute path of the item currently being hovered, but I'd need to dig much deeper for that. For now, I just display the selected item, regardless of which item you hover over. Is that _very_ confusing?

![image](https://cloud.githubusercontent.com/assets/1318438/10976434/202e332c-83ec-11e5-9305-57546c53797f.png)

**Comment by bonsak** [comment]
Great.

**Comment by NiklasRosenstein** [comment]
@bonsak  For the "Properties" dialog, would you want it any smaller than the current minimum size? You'd have to scroll horizontally to reach all elements.

**Comment by bonsak** [comment]
Scrolling is better than having no space left on the screen :) 
450 - 500 px maybe. I'll try to mess with it myself over the weekend.

**Comment by NiklasRosenstein** [comment]
Alright wrapped up in a Scroll Group. ;)

![image](https://cloud.githubusercontent.com/assets/1318438/10977512/c97ee3c2-83f1-11e5-9c43-c44111aa9994.png)

**Comment by bonsak** [comment]
Awesome!

[image: “Bonsak] <http://www.racecar.no>

**Comment by NiklasRosenstein** [comment]
Regarding the "Browser" dialog about the absolute path of the selected item, I don't have a better idea right now. I'll let it stick with showing the path of the selected item on hover over the dialog.

**Comment by bonsak** [comment]
Fine by me.
