### ISSUE TITLE
Update icons in toolbar

### ISSUE THREAD

**Issue by bonsak** [nr-plugins/resedit#6]
Icons should be updated to 32x32px icons and also match more closely the look and feel of Cinema in general.

**Comment by bonsak** [comment]
I can look into this @NiklasRosenstein

**Comment by NiklasRosenstein** [comment]
@bonsak  Maybe we can get Alberto to make some nice icons :grin:

**Comment by NiklasRosenstein** [comment]
Not sure if I'd really like a 32x32 icon palette for this though. Takes up a lot more screen space.

**Comment by bonsak** [comment]
It should be made 32x32 then the user can choose small, med or large them selves. If of course the toolbar was made to be like other toolbars in cinema :) Good idea asking Alberto!

**Comment by NiklasRosenstein** [comment]
Merged your PR #9
