### ISSUE TITLE
Update size of toolbar to take new icons

### ISSUE THREAD

**Issue by bonsak** [nr-plugins/resedit#7]

**Comment by NiklasRosenstein** [comment]
Wouldn't that be involved automatically with #6?

**Comment by bonsak** [comment]
![icons](https://cloud.githubusercontent.com/assets/1322824/10979219/8139acc8-83fb-11e5-9df5-806eb50fede9.jpg)
No. Just tried it with some XParticle icons. No scaling.

**Comment by bonsak** [comment]
The reason it doesn't change size like other toolbars is because it's actually a dialog and not a toolbar.

**Comment by NiklasRosenstein** [comment]
Yes, but we can't make it an actual palette. It would require turning each button into a CommandData plugin and be able to open a palette from code (which I believe is not possible with the SDK).

**Comment by NiklasRosenstein** [comment]
The combobox is just a placeholder, looking to add another button there to toggle 20/32 pixel size icons.

![image](https://cloud.githubusercontent.com/assets/1318438/10980948/fcab2d38-8404-11e5-8dac-df983c0f6f57.png)

**Comment by bonsak** [comment]
![toolbar](https://cloud.githubusercontent.com/assets/1322824/10981148/43dba434-8406-11e5-92a0-180bc3d0ef74.jpg)
You don't want to make it into a proper toolbar so i behaves like all the other toolbars?

**Comment by NiklasRosenstein** [comment]
1. Too much work for now
2. User would need to pop out the toolbar window manually

**Comment by bonsak** [comment]
Ok :)

**Comment by NiklasRosenstein** [comment]
Now right-click menu but items in the dialog menu bar instead. You can also choose a vertical layout and your choice is being remembered.

![image](https://cloud.githubusercontent.com/assets/1318438/10983760/d40ded38-8414-11e5-89af-27b0dc925506.png)

**Comment by bonsak** [comment]
Hey. Thats great!

**Comment by bonsak** [comment]
I made a tmp update to the icons to get the right size: https://github.com/nr-plugins/resedit/pull/9

**Comment by NiklasRosenstein** [comment]
Merged, and 1c9173c fixes the icon size.
